version: '3.1'
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080